language: objective-c

rvm: system

before_install:
  - brew update
  - brew --env
  - brew config

install:
  - mkdir -p $(brew --repo)/Library/Taps/travis
  - ln -s $TRAVIS_BUILD_DIR $(brew --repo)/Library/Taps/travis/homebrew-form

script:
  - brew audit --strict $PACKAGE
  - brew install -v --only-dependencies $PACKAGE $OPTIONS
  - brew install -v $PACKAGE $OPTIONS
  - brew test -v $PACKAGE

notifications:
  email: false

env:
  - PACKAGE=form
  - PACKAGE=form OPTIONS=--HEAD
  # The next line checks all form-*.rb formulae. $(...) is evaluated after
  # the repository is cloned to the working directory on Travis CI.
  - PACKAGE=$(ls form-*.rb | sed 's/\.rb$//')
